name: Sync Fork with Upstream

on:
  schedule:
    # Run every Sunday
    - cron: '0 2 * * 6'
  workflow_dispatch:  # Allow manual trigger of action

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [main, dev]
      fail-fast: false  # Continue with other branches even if one fails
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Sync with Upstream
        id: sync
        run: |
          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Add upstream remote
          git remote add upstream https://github.com/meshcore-dev/MeshCore
          
          # Fetch upstream
          git fetch upstream
          
          # Create a new branch for the sync
          BRANCH_NAME="sync-upstream-${{ matrix.branch }}-$(date +%Y%m%d-%H%M%S)"
          git checkout -b "$BRANCH_NAME"
          
          # Merge upstream branch
          git merge upstream/${{ matrix.branch }} --no-edit
          
          # Push the branch
          git push origin "$BRANCH_NAME"
          
          # Output branch name for PR creation
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --repo nswmesh/MeshCore \
            --base ${{ matrix.branch }} \
            --head ${{ steps.sync.outputs.branch }} \
            --title "[Automated] Sync ${{ matrix.branch }} with upstream" \
            --body "This PR syncs the fork's \`${{ matrix.branch }}\` branch with upstream changes from meshcore-dev/MeshCore.

          Please review and merge if everything looks good.
          
          Automated sync run: ${{ github.run_number }}" \
            --label automated,sync || echo "PR may already exist"
